# Generated by Django 5.0.7 on 2024-08-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myearn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
