# Generated by Django 5.0.7 on 2024-07-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myearn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
    ]
