# Generated by Django 5.0.7 on 2024-08-03 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myearn', '0002_remove_answer_text_question_is_multiple_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myearn.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myearn.usertask'),
        ),
    ]
