# Generated by Django 5.0.7 on 2024-09-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myearn', '0003_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
