# Generated by Django 5.0.7 on 2024-08-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myearn', '0003_alter_answer_question_alter_answer_user_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user_task',
        ),
    ]
