# Generated by Django 5.0.7 on 2024-08-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myearn', '0003_blog_slug_comment_parent_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
