# Generated by Django 5.0.7 on 2024-08-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myearn', '0004_blog_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Podcast', 'Podcast'), ('Audio', 'Audio')], max_length=50),
        ),
    ]
