# Generated by Django 5.0.7 on 2024-08-05 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myearn', '0004_remove_answer_user_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='answer',
            name='user_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myearn.usertask'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
