# Generated by Django 5.0.7 on 2024-08-28 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myearn', '0006_referral_referralreward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='invitee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
    ]
