# Generated by Django 5.0.7 on 2025-01-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myearn', '0008_divicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
