# Generated by Django 5.0.7 on 2025-01-16 01:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myearn', '0009_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divicetoken',
            name='created_at',
        ),
        migrations.AddField(
            model_name='divicetoken',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The last time the token was updated.'),
        ),
        migrations.AddField(
            model_name='divicetoken',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='divicetoken',
            name='token',
            field=models.TextField(help_text='Firebase Cloud Messaging token for the device.'),
        ),
    ]
